# Prácticas básicas con Python

#### Ejercicio 00. Declaración de Variables

Define las siguientes variables con valores que tú elijas:

- Una variable que almacene tu nombre (texto).
- Una variable que almacene tu edad (número entero).
- Una variable que indique si te gusta la programación (verdadero o falso).
- Una variable que almacene tu calificación promedio (número decimal).

In [ ]:
# Declara aquí tus variables.

# Una variable que almacene tu nombre (texto)
name = "Axel"

# Una variable que almacene tu edad (número entero)
age = 30

#Una variable que indique si te gusta la programación (verdadero o falso)
like_to_code = True

#Una variable que almacene tu calificación promedio (número decimal)
qualyfication = 5.0

- Crea una lista con tus cinco números favoritos e imprimelo.

In [ ]:
# Lista de números favoritos
list1 = [27, 7, 13, 15, 22]

# Print de la lista
print(list1)

[27, 7, 13, 15, 22]

- Crea un diccionario que guarde la información de un estudiante e imprimelo:

        - Nombre
        - Edad
        - Calificación final

In [29]:
# Diccionario del estudiante
student = {                   # Variable del diccionario
    "Name": "Axel",           # Par clave-valor "Nombre" : "Nombre del usuario"
    "Age": 30,                # Par clave-valor "Edad" : "Edad del usuario"
    "Final Score": 5.0      # Par clave-valor "Calificación" : "Calificación del usuario"
}

# Print del diccionario
print(student)

{'Name': 'Axel', 'Age': 30, 'Final Score': 5.0}

#### Ejercicio 01. Análisis de datos básico con estructuras nativas de python.
Crea una lista con las calificaciones de 5 estudiantes: [8.5, 9.2, 7.8, 8.9, 10].

- Calcula el promedio de las calificaciones.

In [35]:
# Importamos la librería NumPy
import numpy as np

# Asignamos la lista con la calificación de los 5 estudiantes a la variable "scores"
scores = [8.5, 9.2, 7.8, 8.9, 10]


# Calculamos el promedio de la lista de diferentes formas

# 1. Forma "python puro":
manual_average = sum(scores) / len(scores)


# 2. Media aritmética con NumPy (cuando todos los valores tienen el mismo peso):
arithmetic_mean = np.mean(scores)


# 3. Media ponderada con "NumPy" (cuando la nota final tiene el doble de peso para la media final):
# Tendríamos que añadir una nueva variable con los pesos de cada nota, por ejemplo:
weights = [1, 1, 1, 1, 2]

# Entonces ponemos como primer parámetro la lista de notas "scores" y como parámetro adicional "weights=weights"
weighted_average = np.average(scores, weights=weights)


# Mostramos en la consola los 3 cálculos
print(f"Media aritmética sin NumPy: {manual_average:.2f}")

print(f"Media aritmética: {arithmetic_mean:.2f}")

print(f"Media ponderada: {weighted_average:.2f}")

Media aritmética sin NumPy: 8.88
Media aritmética: 8.88
Media ponderada: 9.07

- Encuentra la calificación más alta y la más baja.

In [27]:
# Para la calificación más alta utilizamos la función integrada max()
print(f"La calificación más alta es: {max(qualyfication)}")

# Para la calificación más baja utilizamos la función integrada min()
print(f"La calificación más baja es: {min(qualyfication)}")

La calificación más alta es: 10
La calificación más baja es: 7.8

# Limpieza de bienes raíces con Pandas para un análisis eficiente 

Este es un conjunto de datos (dataset) reales que fue descargado usando técnicas de web scraping. La data contiene registros de **Fotocasa**, el cual es uno de los sitios más populares de bienes raíces en España. Por favor no hagas esto (web scraping) a no ser que sea para propósitos académicos.

El dataset fue descargado hace algunos años por Henry Navarro y en ningún caso se obtuvo beneficio económico de ello.

Contiene miles de datos de casas reales publicadas en la web www.fotocasa.com. Tu objetivo es extraer tanta información como sea posible con el conocimiento que tienes hasta ahora de ciencia de datos.

¡Comencemos!




- Primero leamos y exploraremos el dataset

In [6]:
import pandas as pd

# Leer el archivo CSV
df = pd.read_csv('assets/real_estate.csv', sep=';') # Este archivo CSV contiene puntos y comas en lugar de comas como separadores
df # mostramos todo

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

- Muestra las primeras filas del archivo CSV

In [7]:
# Mostrar las primeras filas
"""first_row = pd.DataFrame(df, index=[0])
first_row"""

df.head(10)

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
5,6,153934794,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,70.0,315000,...,0,0,0,0,0,0,"40,53391","-3,89445",NaN,NaN
6,7,153848236,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,145.0,430000,...,0,0,0,0,0,0,"40,5105842135624","-3,89436578643763",NaN,NaN
7,8,153482331,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,95.0,275000,...,0,0,0,0,0,0,"40,53294","-3,89898",NaN,NaN
8,9,153885351,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,3.0,277.0,445000,...,0,0,0,0,0,0,"40,5363057864376","-3,89294421356237",NaN,NaN
9,10,153215459,False,modesta,NaN,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,129.0,350000,...,0,0,0,0,0,0,"40,37502","-3,74391",NaN,NaN

Perfecto, esto fue una pequeña practica. ¡Ahora empecemos con los verdaderos ejercicios!

#### Ejercicio 01. ¿Cuál es la casa más cara en todo el dataset? (★☆☆)

Imprime la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle del Prado, Nº20 es la más cara y su precio es de 5000000 USD`

In [8]:
max_price = max(list(df["price"]))
max_price_index = df['price'].idxmax()

address = df.loc[max_price_index, "address"]






print(f"La casa con dirección en {address} es la más cara y su precio es de {max_price} USD")

La casa con dirección en El Escorial es la más cara y su precio es de 8500000 USD

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15335 entries, 0 to 15334
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        15335 non-null  int64
 1   id_realEstates    15335 non-null  int64
 2   isNew             15335 non-null  bool
 3   realEstate_name   15325 non-null  object
 4   phone_realEstate  14541 non-null  float64
 5   url_inmueble      15335 non-null  object
 6   rooms             14982 non-null  float64
 7   bathrooms         14990 non-null  float64
 8   surface           14085 non-null  float64
 9   price             15335 non-null  int64
 10  date              15335 non-null  object
 11  description       15193 non-null  object
 12  address           15335 non-null  object
 13  country           15335 non-null  object
 14  level1            15335 non-null  object
 15  level2            15335 non-null  object
 16  level3            15335 non-null  object
 17  level4            8692 non-null   object
 18  level5            15335 non-null  object
 19  level6            708 non-null    object
 20  level7            13058 non-null  object
 21  level8            6756 non-null   object
 22  upperLevel        15335 non-null  object
 23  countryId         15335 non-null  int64
 24  level1Id          15335 non-null  int64
 25  level2Id          15335 non-null  int64
 26  level3Id          15335 non-null  int64
 27  level4Id          15335 non-null  int64
 28  level5Id          15335 non-null  int64
 29  level6Id          15335 non-null  int64
 30  level7Id          15335 non-null  int64
 31  level8Id          15335 non-null  int64
 32  accuracy          15335 non-null  int64
 33  latitude          15335 non-null  object
 34  longitude         15335 non-null  object
 35  zipCode           0 non-null      float64
 36  customZone        0 non-null      float64
dtypes: bool(1), float64(6), int64(13), object(17)
memory usage: 4.2+ MB

#### Ejercicio 02. ¿Cuál es la casa más barata del dataset? (★☆☆)

Este ejercicio es similar al ejercicio anterior, solo que ahora buscamos la casa con el precio más bajo. Recuerda imprimir la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle Alcalá, Nº58 es la más barata y su precio es de 12000 USD`

In [10]:
# Primero buscamos el precio mínimo en la lista y lo asignamos a 'min_price'.
min_price = min(list(df["price"]))
# Problema: min_price = 0


# Como vemos que hay precios que son 0, los vamos a filtrar porque damos por sentado que no son datos que podamos tener en cuenta por el contexto.
# Para ello, creamos un nuevo DataFrame que nos filtre los 0 y lo asignamos a 'df_filtered_price'.
df_filtered_price = df[df['price'] > 0]


# Ahora que ya tenemos un dataframe que no tiene en cuenta las casas con un 'price' = 0, buscamos el precio mínimo y lo asignamos a 'min_price_filtered'.
min_price_filtered = df_filtered_price["price"].idxmin()




# Ya con el row correcto, podemos localizar el contenido de la celda 'datos_completos' con el método '.loc()'. 
datos_completos_min = df.loc[min_price_filtered]


# Ya tenemos la información para el ejercicio asi que mostramos en la terminal el resultado con la f-string correspondiente.
print(f"La casa con dirección en {datos_completos_min['address']} es la más barata y su precio es de {datos_completos_min['price']} USD")

La casa con dirección en Berlin, Coslada es la más barata y su precio es de 600 USD

In [11]:

df.loc[df['price'] == 600]

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
7491,7492,153977752,False,redpiso coslada,910759552.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,80.0,600,...,0,0,0,0,0,0,"40,41869","-3,54004",NaN,NaN

In [19]:
df_filtered_surface = df[df['surface'] > 0]

surface_filtered_idx_max = df_filtered_surface["surface"].idxmax()
surface_filtered_idx_min = df_filtered_surface["surface"].idxmin()


print(df.loc[surface_filtered_idx_max, 'surface'])
print(df.loc[surface_filtered_idx_min, 'surface'])

249000.0
15.0

#### Ejercicio 03. ¿Cuál es la casa más grande y la más pequeña del dataset? (★☆☆)

Imprime la dirección y el área de las casas seleccionadas. Por ejemplo:

`La casa más grande está ubicada en Calle Gran Vía, Nº38 y su superficie es de 5000 metros`

`La casa más pequeña está ubicada en Calle Mayor, Nº12 y su superficie es de 200 metros`

Este ejercicio es similar al anterior, pero buscamos las casas más grandes y pequeñas en base a su superficie.

In [13]:
df_filtered_surface = df[df['surface'] > 0]

surface_filtered_idx_max = df_filtered_surface["surface"].idxmax()
surface_filtered_idx_min = df_filtered_surface["surface"].idxmin()


print(f'La casa más grande está ubicada en {df.loc[surface_filtered_idx_max, 'address']} y su superficie es de {df.loc[surface_filtered_idx_max, 'surface']} metros')

print(f'La casa más pequeña está ubicada en {df.loc[surface_filtered_idx_min, 'address']} y su superficie es de {df.loc[surface_filtered_idx_min, 'surface']} metros')

La casa más grande está ubicada en Sevilla la Nueva y su superficie es de 249000.0 metros
La casa más pequeña está ubicada en Calle Amparo,  Madrid Capital y su superficie es de 15.0 metros

#### Ejercicio 04. ¿Cuantas poblaciones contiene el dataset? (★☆☆)

Cuenta el número de poblaciones únicas en la columna 'level5' e imprime el nombre de las poblaciones separadas por coma. Por ejemplo:

`> print(populations)`

`population1, population2, population3, ...`

In [14]:
columnas = df['level5']
extraccion = columnas.unique()
print(extraccion)

['Arganda del Rey' 'Fuenlabrada' 'Boadilla del Monte'
 'Las Rozas de Madrid' ' Madrid Capital' 'Villaviciosa de Odón' 'Pinto'
 'Valdemoro' 'Navalcarnero' 'Pozuelo de Alarcón' 'Torrejón de Ardoz'
 'Navalagamella' 'San Sebastián de los Reyes' 'Rivas-vaciamadrid'
 'Alpedrete' 'Móstoles' 'San Fernando de Henares' 'Coslada'
 'Becerril de la Sierra' 'Alcalá de Henares' 'Chinchón' 'Parla' 'Alcorcón'
 'El Escorial' 'Leganés' 'Pedrezuela' 'Majadahonda'
 'Villanueva de la Cañada' 'Villanueva del Pardillo' 'Torrelodones'
 'Moralzarzal' 'Mejorada del Campo' 'Aranjuez' 'Corpa' 'Getafe'
 'Velilla de San Antonio' 'Sevilla la Nueva' 'San Martín de la Vega'
 'Villalbilla' 'Collado Villalba' 'Alcobendas' 'El Molar (Madrid)'
 'Moraleja de Enmedio' 'Algete' 'Campo Real' 'Torrejón de la Calzada'
 'Colmenar Viejo' 'Valdemorillo' 'Fuente El Saz de Jarama' 'Tres Cantos'
 'Arroyomolinos (Madrid)' 'Griñón' 'Paracuellos de Jarama' 'Guadarrama'
 'Titulcia' 'Galapagar' 'Collado Mediano' 'Los Molinos'
 'San Lorenzo de El Escorial' 'Loeches' 'San Martín de Valdeiglesias'
 'Navas del Rey' 'Bustarviejo' 'Manzanares El Real' 'Carabaña'
 'Casarrubuelos' 'Cercedilla' 'Fresnedillas de la Oliva' 'Valdemaqueda'
 'Robledo de Chavela' 'Miraflores de la Sierra' 'Humanes de Madrid'
 'Valdetorres de Jarama' 'San Agustín del Guadalix' 'Ciempozuelos'
 'Camarma de Esteruelas' 'Torres de la Alameda' 'Talamanca de Jarama'
 'El Atazar' 'Hoyo de Manzanares' 'El Boalo - Cerceda – Mataelpino'
 'El Álamo' 'Valdilecha' 'Valdeolmos-Alalpardo' 'Guadalix de la Sierra'
 'Belmonte de Tajo' 'El Vellón' 'Brunete' 'Redueña' 'Morata de Tajuña'
 'Tielmes' 'Gargantilla del Lozoya' 'Meco' 'Venturada' 'Quijorna'
 'Cenicientos' 'Torrejón de Velasco' 'Navacerrada'
 'Santa María de la Alameda' 'Orusco de Tajuña' 'Daganzo de Arriba'
 'Villamanta' 'Anchuelo' 'Valdaracete' 'Ajalvir' 'Los Santos de la Humosa'
 'Villamanrique de Tajo' 'Colmenar de Oreja' 'Villa del Prado'
 'Fuentidueña de Tajo' 'Colmenar del Arroyo' 'Valdelaguna'
 'Cubas de la Sagra' 'Valdeavero' 'Aldea del Fresno' 'Ribatejada'
 'Torrelaguna' 'Batres' 'Pezuela de las Torres' 'Colmenarejo'
 'Serranillos del Valle' 'Cobeña' 'Soto del Real' 'El Berrueco'
 'Villanueva de Perales' 'Fresno de Torote - Serracines' 'Pozuelo del Rey'
 'Pelayos de la Presa' 'La Cabrera' 'Nuevo Baztán' 'Perales de Tajuña'
 'Villaconejos' 'Villarejo de Salvanés' 'Cadalso de los Vidrios'
 'Santorcaz' 'Madarcos' 'Garganta de los Montes' 'Puentes Viejas'
 'Torremocha de Jarama' 'Valdemanco' 'Braojos'
 'Lozoyuela-navas-sieteiglesias' 'Piñuécar-gandullas' 'Valdepiélagos'
 'Valverde de Alcalá' 'Villar del Olmo' 'Villamantilla'
 'Horcajo de la Sierra' 'Gascones' 'Zarzalejo' 'Villavieja del Lozoya'
 'Brea de Tajo' 'Estremera' 'Chapinería' 'Navarredonda' 'Patones' 'Ambite'
 'Navalafuente' 'Lozoya' 'Canencia' 'Cabanillas de la Sierra'
 'Buitrago del Lozoya' 'Fresno de Torote' 'Robregordo' 'Pinilla del Valle'
 'Rascafría' 'La Hiruela' 'Montejo de la Sierra']

#### Ejercicio 05. ¿El dataset contiene valores nulos (NAs)? (★☆☆)

Imprima un booleano (`True` o `False`) para verificar si hay valores nulos seguido de las columnas que contiene el NAs.

In [15]:
is_bool = df.isnull()
is_bool_con_any = df.isnull().any()

print(is_bool_con_any)

Unnamed: 0          False
id_realEstates      False
isNew               False
realEstate_name      True
phone_realEstate     True
url_inmueble        False
rooms                True
bathrooms            True
surface              True
price               False
date                False
description          True
address             False
country             False
level1              False
level2              False
level3              False
level4               True
level5              False
level6               True
level7               True
level8               True
upperLevel          False
countryId           False
level1Id            False
level2Id            False
level3Id            False
level4Id            False
level5Id            False
level6Id            False
level7Id            False
level8Id            False
accuracy            False
latitude            False
longitude           False
zipCode              True
customZone           True
dtype: bool

#### Ejercicio 06. Elimina los valores nulos (NAs) del dataset, si aplica (★★☆)

Despues de eliminar los valores nulos, compara el tamaño del DataFrame antes y después de la eliminación.

In [16]:
csv_without_nan = df.dropna(how='all') # Elimina si tiene todos los valores nulos
csv_without_null = df.dropna() # Elimina si tiene valores nulos

print(len(df))
print(len(csv_without_nan))
print(len(csv_without_null))

15335
15335
0

#### Ejercicio 07. ¿Cuál es la media de precios en la población de "Arroyomolinos (Madrid)"? (★★☆)

Imprima el valor obtenido de la columna level5.

In [17]:
import numpy as np

arroyomolinos = df[df['level5'] == 'Arroyomolinos (Madrid)']

# media = np.mean(list(arroyomolinos['price']))

int(np.average(arroyomolinos['price']))
int(np.mean(arroyomolinos['price']))

294541

#### Ejercicio 08. Trazar el histograma de los precios para la población de "Arroyomolinos (Madrid)" y explica qué observas (★★☆)

Imprime el histograma de los precios y escribe en la celda del Markdown un breve análisis del trazado.

In [ ]:
import matplotlib.pyplot as plt

# Trazar el histograma de precios
# 1. Crear o cargar datos
data = {'valores': [1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6]}
df = pd.DataFrame(data)

# 2. Trazar histograma básico
plt.hist(df['valores'], bins=5, edgecolor='black')

# 3. Personalizar y mostrar
plt.title('Histograma Básico')
plt.xlabel('Intervalos')
plt.ylabel('Frecuencia')
plt.show()

**TODO: Markdown**. Para escribir aquí, haz doble clic en esta celda, elimina este contenido y coloca lo que quieras escribir. Luego ejecuta la celda.