# Prácticas básicas con Python

#### Ejercicio 00. Declaración de Variables

Define las siguientes variables con valores que tú elijas:

- Una variable que almacene tu nombre (texto).
- Una variable que almacene tu edad (número entero).
- Una variable que indique si te gusta la programación (verdadero o falso).
- Una variable que almacene tu calificación promedio (número decimal).

In [5]:
# Declara aquí tus variables.
name = "Axel"
age = 30
like_to_code = True
qualyfication = 5.0


#Ejemplo
saludo = "Hola mundo"

- Crea una lista con tus cinco números favoritos e imprimelo.

In [6]:
# Lista de números favoritos

lista = [27, 7, 13, 15, 22]
print(lista)

[27, 7, 13, 15, 22]

- Crea un diccionario que guarde la información de un estudiante e imprimelo:

        - Nombre
        - Edad
        - Calificación final

In [7]:
# Diccionario del estudiante
student = {
    "Name": "Axel",
    "Age": 30,
    "Qualyfication": 5.0    
}

print(student)

{'Name': 'Axel', 'Age': 30, 'Qualyfication': 5.0}

#### Ejercicio 01. Análisis de datos básico con estructuras nativas de python.
Crea una lista con las calificaciones de 5 estudiantes: [8.5, 9.2, 7.8, 8.9, 10].

- Calcula el promedio de las calificaciones.

In [18]:
# Código
import numpy as np

qualyfications = [8.5, 9.2, 7.8, 8.9, 10]

average_mean = np.mean(qualyfications)
average = np.average(qualyfications)

print(average_mean)
print(average)

8.879999999999999
8.879999999999999

- Encuentra la calificación más alta y la más baja.

In [19]:
# Código
print(f"La calificación más alta es: {max(qualyfications)}")
print(f"La calificación más baja es: {min(qualyfications)}")

La calificación más alta es: 10
La calificación más baja es: 7.8

# Limpieza de bienes raíces con Pandas para un análisis eficiente 

Este es un conjunto de datos (dataset) reales que fue descargado usando técnicas de web scraping. La data contiene registros de **Fotocasa**, el cual es uno de los sitios más populares de bienes raíces en España. Por favor no hagas esto (web scraping) a no ser que sea para propósitos académicos.

El dataset fue descargado hace algunos años por Henry Navarro y en ningún caso se obtuvo beneficio económico de ello.

Contiene miles de datos de casas reales publicadas en la web www.fotocasa.com. Tu objetivo es extraer tanta información como sea posible con el conocimiento que tienes hasta ahora de ciencia de datos.

¡Comencemos!




- Primero leamos y exploraremos el dataset

In [56]:
import pandas as pd

# Leer el archivo CSV
df = pd.read_csv('assets/real_estate.csv', sep=';') # Este archivo CSV contiene puntos y comas en lugar de comas como separadores
df # mostramos todo

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

- Muestra las primeras filas del archivo CSV

In [72]:
# Mostrar las primeras filas
first_row = pd.DataFrame(df, index=[13110])
first_row

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
13110,13111,132042636,False,engel volkers torrelodones,911798512.0,https://www.fotocasa.es/es/comprar/vivienda/vi...,19.0,NaN,NaN,8500000,...,0,0,0,0,0,0,"40,5830801751782","-4,12951942848611",NaN,NaN

Perfecto, esto fue una pequeña practica. ¡Ahora empecemos con los verdaderos ejercicios!

#### Ejercicio 01. ¿Cuál es la casa más cara en todo el dataset? (★☆☆)

Imprime la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle del Prado, Nº20 es la más cara y su precio es de 5000000 USD`

In [ ]:
max_price = max(list(df["price"]))
max_price_id = df['price'].idxmax()

address = df.loc[max_price_id, "address"]






print(f"La casa con dirección en {address} es la más cara y su precio es de {max_price} USD")

La casa con dirección en El Escorial es la más cara y su precio es de 8500000 USD
13110

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15335 entries, 0 to 15334
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        15335 non-null  int64
 1   id_realEstates    15335 non-null  int64
 2   isNew             15335 non-null  bool
 3   realEstate_name   15325 non-null  object
 4   phone_realEstate  14541 non-null  float64
 5   url_inmueble      15335 non-null  object
 6   rooms             14982 non-null  float64
 7   bathrooms         14990 non-null  float64
 8   surface           14085 non-null  float64
 9   price             15335 non-null  int64
 10  date              15335 non-null  object
 11  description       15193 non-null  object
 12  address           15335 non-null  object
 13  country           15335 non-null  object
 14  level1            15335 non-null  object
 15  level2            15335 non-null  object
 16  level3            15335 non-null  object
 17  level4            8692 non-null   object
 18  level5            15335 non-null  object
 19  level6            708 non-null    object
 20  level7            13058 non-null  object
 21  level8            6756 non-null   object
 22  upperLevel        15335 non-null  object
 23  countryId         15335 non-null  int64
 24  level1Id          15335 non-null  int64
 25  level2Id          15335 non-null  int64
 26  level3Id          15335 non-null  int64
 27  level4Id          15335 non-null  int64
 28  level5Id          15335 non-null  int64
 29  level6Id          15335 non-null  int64
 30  level7Id          15335 non-null  int64
 31  level8Id          15335 non-null  int64
 32  accuracy          15335 non-null  int64
 33  latitude          15335 non-null  object
 34  longitude         15335 non-null  object
 35  zipCode           0 non-null      float64
 36  customZone        0 non-null      float64
dtypes: bool(1), float64(6), int64(13), object(17)
memory usage: 4.2+ MB

#### Ejercicio 02. ¿Cuál es la casa más barata del dataset? (★☆☆)

Este ejercicio es similar al ejercicio anterior, solo que ahora buscamos la casa con el precio más bajo. Recuerda imprimir la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle Alcalá, Nº58 es la más barata y su precio es de 12000 USD`

In [ ]:
min_price = min(list(df["price"]))
lista_precios = list(df["price"])


df_filtered = df[df['price'] > 0]

for _ in lista_precios:
    




min_price_id = df_filtered["price"].idxmin()

address = df.loc[df_filtered, "address"]






print(f"La casa con dirección en {address} es la más barata y su precio es de {min_price_id} USD")

TypeError: 'str' object is not callable

In [124]:

df.loc[df['price'] == 600]

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
7491,7492,153977752,False,redpiso coslada,910759552.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,80.0,600,...,0,0,0,0,0,0,"40,41869","-3,54004",NaN,NaN

In [ ]:
df_filtered = df[df['price'] > 0]

df_filtered["price"].idxmin()

np.int64(7491)

#### Ejercicio 03. ¿Cuál es la casa más grande y la más pequeña del dataset? (★☆☆)

Imprime la dirección y el área de las casas seleccionadas. Por ejemplo:

`La casa más grande está ubicada en Calle Gran Vía, Nº38 y su superficie es de 5000 metros`

`La casa más pequeña está ubicada en Calle Mayor, Nº12 y su superficie es de 200 metros`

Este ejercicio es similar al anterior, pero buscamos las casas más grandes y pequeñas en base a su superficie.

In [ ]:
# TODO

#### Ejercicio 04. ¿Cuantas poblaciones contiene el dataset? (★☆☆)

Cuenta el número de poblaciones únicas en la columna 'level5' e imprime el nombre de las poblaciones separadas por coma. Por ejemplo:

`> print(populations)`

`population1, population2, population3, ...`

In [ ]:
# TODO

#### Ejercicio 05. ¿El dataset contiene valores nulos (NAs)? (★☆☆)

Imprima un booleano (`True` o `False`) para verificar si hay valores nulos seguido de las columnas que contiene el NAs.

In [ ]:
# TODO

#### Ejercicio 06. Elimina los valores nulos (NAs) del dataset, si aplica (★★☆)

Despues de eliminar los valores nulos, compara el tamaño del DataFrame antes y después de la eliminación.

In [ ]:
# TODO

#### Ejercicio 07. ¿Cuál es la media de precios en la población de "Arroyomolinos (Madrid)"? (★★☆)

Imprima el valor obtenido de la columna level5.

In [ ]:
# TODO

#### Ejercicio 08. Trazar el histograma de los precios para la población de "Arroyomolinos (Madrid)" y explica qué observas (★★☆)

Imprime el histograma de los precios y escribe en la celda del Markdown un breve análisis del trazado.

In [ ]:
import matplotlib.pyplot as plt

# Trazar el histograma de precios

**TODO: Markdown**. Para escribir aquí, haz doble clic en esta celda, elimina este contenido y coloca lo que quieras escribir. Luego ejecuta la celda.